POSTGRES_DB: 'your preferred database name'
POSTGRES_TEST_DB: 'your preferred test database name'
POSTGRES_USER: 'your postgres  user'
POSTGRES_PASSWORD: 'your postgres password'
POSTGRES_HOST: 'your preferred localhost for postgress; recommend `localhost`'
